#!/bin/bash

wget --output-document=- --quiet \
  https://boardgamegeek.com/xmlapi/geeklist/146056?comments=1 \
  | cabal run --verbose=0 > new

if [ ! -e cur ]; then touch cur; fi

diff cur new
RES=$?

if [ $RES == 0 ]; then rm new; fi


